name: Replace Old Phrase

on:
  push:
    branches:
      - dev

jobs:
  replace-phrase-and-rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Replace old phrase with new phrase in files
      run: |
        old_phrase="malopieds"
        new_phrase="moxxaxx"
        find . -type f -name "*.java" -o -name "*.kt" -o -name "AndroidManifest.xml" -o -name "build.gradle" -o -name "build.gradle.kts" -o -name "*.xml" -o -name "*.md" | xargs sed -i "s/${old_phrase}/${new_phrase}/g"
        echo "Replaced '${old_phrase}' with '${new_phrase}' in all files:"
        grep -r "${new_phrase}" .

    - name: Rename directories containing old phrase
      run: |
        old_phrase="malopieds"
        new_phrase="moxxaxx"
        find . -depth -type d -name "*${old_phrase}*" | while read dir; do
          new_dir=$(echo $dir | sed "s/${old_phrase}/${new_phrase}/g")
          mv "$dir" "$new_dir"
        done
        echo "Renamed directories containing '${old_phrase}' to '${new_phrase}'"
        find . -type d -name "*${new_phrase}*"

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git status
        git commit -m "Replaced '${old_phrase}' with '${new_phrase}' in all files and renamed directories" || echo "Nothing to commit"
        git push || echo "Nothing to push"
