name: Replace ColdSoup with Metrolist

on:
  push:
    branches:
      - dev

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace ColdSoup with Metrolist in all files
      run: |
        old_word="ColdSoup"
        new_word="Metrolist"
        
        # Replace the old word with the new word in all files
        find . -type f -exec sed -i "s/$old_word/$new_word/g" {} +

        # Optional: Display files with changes
        echo "Files with changes:"
        grep -rl "$new_word" .

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git status
        git commit -m "Replaced $old_word with $new_word in files" || echo "Nothing to commit"
        git push || echo "Nothing to push"
