name: Change Package Name

on:
  push:
    branches:
      - dev

jobs:
  update-package-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Update package name in files
      run: |
        find . -type f -name "*.java" -o -name "*.kt" -o -name "AndroidManifest.xml" -o -name "build.gradle" -o -name "build.gradle.kts" | xargs sed -i 's/com.malopieds.innertune/com.moxxaxx.music/g'
        echo "Updated package names in files:"
        grep -r 'com.moxxaxx.music' .

    - name: Print directory structure before rename
      run: |
        echo "Before renaming directories:"
        find . -type d

    - name: Rename directories
      run: |
        old_base_dir=$(find . -type d -path "*/com/malopieds/innertune")
        for base_dir in $old_base_dir; do
          new_base_dir=$(echo $base_dir | sed 's/com\/malopieds\/innertune/com\/moxxaxx\/music/')
          mkdir -p "$(dirname "$new_base_dir")"
          mv "$base_dir" "$new_base_dir"
        done
        echo "Renamed directories:"
        find . -type d -path "*/com/moxxaxx/music"

    - name: Print directory structure after rename
      run: |
        echo "After renaming directories:"
        find . -type d

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git status
        git commit -m "Update package name and directories from com.malopieds.innertune to com.moxxaxx.music" || echo "Nothing to commit"
        git push || echo "Nothing to push"
