name: Release APK

on:
  release:
    types: [created]

jobs:
  upload-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify APK file exists
      run: |
        if [ ! -f app/build/outputs/apk/foss/release/app-foss-release.apk ]; then
          echo "APK file not found!"
          exit 1
        fi

    - name: Upload APK as a GitHub Release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: app/build/outputs/apk/foss/release/app-foss-release.apk
        asset_name: app-foss-release.apk
        asset_content_type: application/vnd.android.package-archive
