name: Sign Android App

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  sign:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Download APK from build job
      uses: actions/download-artifact@v2
      with:
        name: app
        path: app/build/outputs/apk/foss/release/

    - name: Sign APK
      run: |
        jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore -storepass android -keypass android app/build/outputs/apk/foss/release/app-release-unsigned.apk androiddebugkey
        zipalign -v 4 app/build/outputs/apk/foss/release/app-release-unsigned.apk app/build/outputs/apk/foss/release/app-release.apk

    - name: Upload Signed APK
      uses: actions/upload-artifact@v3
      with:
        name: signed-app
        path: app/build/outputs/apk/foss/release/app-release.apk
